apiVersion: v1
kind: ResourceQuota
metadata:
  name: openedx-quota
  namespace: openedx
spec:
  hard:
    pods: "20"
    requests.cpu: "4"
    requests.memory: "8Gi"
    limits.cpu: "8"
    limits.memory: "16Gi"
