apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openedx-admin
  namespace: openedx
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
  ---
  apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openedx-developer
  namespace: openedx
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
